"""Fine-tune ZipVoice with prompt-prefix conditioning.

The training manifest must be generated by prepare_manifest.py. Each cut contains
prompt + short silence + target audio. The loss is computed only on target frames.
"""

from __future__ import annotations

import argparse
import json
import logging
import shutil
from pathlib import Path
from types import SimpleNamespace
from typing import Any

import torch
from lhotse import CutSet, load_manifest_lazy
from zipvoice.bin.train_zipvoice import tokenize_text
from zipvoice.dataset.datamodule import TtsDataModule
from zipvoice.models.zipvoice import ZipVoice
from zipvoice.tokenizer.tokenizer import EmiliaTokenizer, EspeakTokenizer, LibriTTSTokenizer, SimpleTokenizer
from zipvoice.utils.checkpoint import load_checkpoint, save_checkpoint
from zipvoice.utils.common import (
    AttributeDict,
    GradScaler,
    create_grad_scaler,
    get_parameter_groups_with_lrs,
    prepare_input,
    torch_autocast,
)
from zipvoice.utils.optim import ScaledAdam


def prompt_frames_from_cuts(cuts: list[Any], features_lens: torch.Tensor) -> torch.Tensor:
    frames = []
    for cut, feature_len in zip(cuts, features_lens.tolist(), strict=True):
        prompt_seconds = float(cut.custom["prompt_condition_duration_seconds"])
        cut_duration = max(float(cut.duration), 1e-6)
        prompt_frames = int(round(prompt_seconds / cut_duration * int(feature_len)))
        prompt_frames = max(0, min(prompt_frames, int(feature_len) - 1))
        frames.append(prompt_frames)
    return torch.tensor(frames, dtype=torch.int64, device=features_lens.device)


def build_prefix_target_mask(
    features_lens: torch.Tensor,
    prompt_frames: torch.Tensor,
    max_len: int | None = None,
) -> torch.Tensor:
    max_len = int(max_len or features_lens.max().item())
    seq_range = torch.arange(max_len, device=features_lens.device)
    return (seq_range[None, :] >= prompt_frames[:, None]) & (
        seq_range[None, :] < features_lens[:, None]
    )


def compute_prefix_fbank_loss(
    model: ZipVoice,
    features: torch.Tensor,
    features_lens: torch.Tensor,
    tokens: list[list[int]],
    prompt_frames: torch.Tensor,
    condition_drop_ratio: float,
    is_training: bool,
) -> tuple[torch.Tensor, dict[str, float]]:
    batch_size = features.shape[0]
    noise = torch.randn_like(features)
    if is_training:
        t = torch.rand(batch_size, 1, 1, device=features.device)
    else:
        t = (
            (torch.arange(batch_size, device=features.device) / batch_size)
            .unsqueeze(1)
            .unsqueeze(2)
        )
    text_condition, padding_mask = model.forward_text_train(
        tokens=tokens,
        features_lens=features_lens,
    )
    target_mask = build_prefix_target_mask(
        features_lens=features_lens,
        prompt_frames=prompt_frames,
        max_len=features.size(1),
    )
    speech_condition = torch.where(target_mask.unsqueeze(-1), 0, features)
    if condition_drop_ratio > 0.0:
        drop_mask = (
            torch.rand(text_condition.size(0), 1, 1, device=text_condition.device)
            > condition_drop_ratio
        )
        text_condition = text_condition * drop_mask
    xt = features * t + noise * (1 - t)
    ut = features - noise
    vt = model.forward_fm_decoder(
        t=t,
        xt=xt,
        text_condition=text_condition,
        speech_condition=speech_condition,
        padding_mask=padding_mask,
    )
    loss_mask = target_mask & (~padding_mask)
    loss = torch.mean((vt[loss_mask] - ut[loss_mask]) ** 2)
    return loss, {
        "loss": float(loss.detach().cpu().item()),
        "target_frames": float(loss_mask.sum().detach().cpu().item()),
    }


def get_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--train-manifest", type=Path, required=True)
    parser.add_argument("--dev-manifest", type=Path, required=True)
    parser.add_argument("--model-config", type=Path, required=True)
    parser.add_argument("--checkpoint", type=Path, required=True)
    parser.add_argument("--token-file", type=Path, required=True)
    parser.add_argument("--tokenizer", default="emilia")
    parser.add_argument("--lang", default="en-us")
    parser.add_argument("--exp-dir", type=Path, required=True)
    parser.add_argument("--num-iters", type=int, default=4000)
    parser.add_argument("--save-every-n", type=int, default=500)
    parser.add_argument("--valid-interval", type=int, default=500)
    parser.add_argument("--base-lr", type=float, default=6e-6)
    parser.add_argument("--max-duration", type=float, default=120.0)
    parser.add_argument("--min-len", type=float, default=0.5)
    parser.add_argument("--max-len", type=float, default=30.0)
    parser.add_argument("--num-workers", type=int, default=4)
    parser.add_argument("--num-buckets", type=int, default=20)
    parser.add_argument("--use-fp16", type=int, default=0)
    parser.add_argument("--feat-scale", type=float, default=0.1)
    parser.add_argument("--condition-drop-ratio", type=float, default=0.2)
    parser.add_argument("--seed", type=int, default=20260514)
    parser.add_argument("--log-interval", type=int, default=25)
    return parser


def main(argv: list[str] | None = None) -> None:
    args = get_parser().parse_args(argv)
    args.exp_dir.mkdir(parents=True, exist_ok=True)
    setup_logging(args.exp_dir)
    torch.manual_seed(args.seed)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

    tokenizer = build_tokenizer(args)
    tokenizer_config = {"vocab_size": tokenizer.vocab_size, "pad_id": tokenizer.pad_id}
    model_config = json.loads(args.model_config.read_text(encoding="utf-8"))
    model = ZipVoice(**model_config["model"], **tokenizer_config)
    load_checkpoint(args.checkpoint, model=model, strict=True)
    model = model.to(device)
    logging.info("Loaded checkpoint from %s", args.checkpoint)

    train_dl = build_dataloader(args, load_and_tokenize_cuts(args.train_manifest, tokenizer, args), True)
    dev_dl = build_dataloader(args, load_and_tokenize_cuts(args.dev_manifest, tokenizer, args), False)
    optimizer = ScaledAdam(
        get_parameter_groups_with_lrs(model, lr=args.base_lr, include_names=True),
        lr=args.base_lr,
        clipping_scale=2.0,
    )
    scaler = create_grad_scaler(enabled=bool(args.use_fp16))
    params = AttributeDict({"feat_scale": args.feat_scale, "best_valid_loss": float("inf"), "best_iter": 0})
    copy_runtime_files(args)

    train_iter = iter(train_dl)
    last_train_loss = None
    for batch_idx in range(1, args.num_iters + 1):
        try:
            batch = next(train_iter)
        except StopIteration:
            train_iter = iter(train_dl)
            batch = next(train_iter)
        model.train()
        tokens, features, features_lens = prepare_input(params, batch, device, True, True)
        prompt_frames = prompt_frames_from_cuts(batch["cut"], features_lens)
        optimizer.zero_grad()
        with torch_autocast(dtype=torch.float16, enabled=bool(args.use_fp16)):
            loss, info = compute_prefix_fbank_loss(
                model,
                features,
                features_lens,
                tokens,
                prompt_frames,
                args.condition_drop_ratio,
                True,
            )
        scaler.scale(loss).backward()
        scaler.step(optimizer)
        scaler.update()
        last_train_loss = info["loss"]
        if batch_idx == 1 or batch_idx % args.log_interval == 0:
            logging.info("iter=%s train_loss=%.6f", batch_idx, info["loss"])
        if batch_idx % args.valid_interval == 0 or batch_idx == args.num_iters:
            valid_loss = compute_validation_loss(args, params, model, dev_dl, device)
            logging.info("iter=%s valid_loss=%.6f", batch_idx, valid_loss)
            if valid_loss < params.best_valid_loss:
                params.best_valid_loss = valid_loss
                params.best_iter = batch_idx
                save_model_checkpoint(args.exp_dir / "best-valid-loss.pt", model, optimizer, scaler, batch_idx, valid_loss)
        if batch_idx % args.save_every_n == 0 or batch_idx == args.num_iters:
            save_model_checkpoint(
                args.exp_dir / f"checkpoint-{batch_idx}.pt",
                model,
                optimizer,
                scaler,
                batch_idx,
                params.best_valid_loss,
            )

    summary = {
        "best_iter": params.best_iter,
        "best_valid_loss": params.best_valid_loss,
        "last_train_loss": last_train_loss,
        "num_iters": args.num_iters,
        "max_cuda_memory_mb": int(torch.cuda.max_memory_allocated() // 1_000_000)
        if torch.cuda.is_available()
        else None,
    }
    (args.exp_dir / "train_summary.json").write_text(
        json.dumps(summary, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def compute_validation_loss(args: argparse.Namespace, params: AttributeDict, model: ZipVoice, dev_dl: torch.utils.data.DataLoader, device: torch.device) -> float:
    model.eval()
    total_loss = 0.0
    total_frames = 0.0
    with torch.no_grad():
        for batch in dev_dl:
            tokens, features, features_lens = prepare_input(params, batch, device, True, True)
            prompt_frames = prompt_frames_from_cuts(batch["cut"], features_lens)
            loss, info = compute_prefix_fbank_loss(model, features, features_lens, tokens, prompt_frames, 0.0, False)
            frames = max(info["target_frames"], 1.0)
            total_loss += float(loss.detach().cpu().item()) * frames
            total_frames += frames
    return total_loss / max(total_frames, 1.0)


def build_tokenizer(args: argparse.Namespace) -> Any:
    if args.tokenizer == "emilia":
        return EmiliaTokenizer(token_file=args.token_file)
    if args.tokenizer == "libritts":
        return LibriTTSTokenizer(token_file=args.token_file)
    if args.tokenizer == "espeak":
        return EspeakTokenizer(token_file=args.token_file, lang=args.lang)
    if args.tokenizer == "simple":
        return SimpleTokenizer(token_file=args.token_file)
    raise ValueError(f"unsupported tokenizer: {args.tokenizer}")


def load_and_tokenize_cuts(manifest: Path, tokenizer: Any, args: argparse.Namespace) -> CutSet:
    cuts = load_manifest_lazy(manifest)
    cuts = cuts.filter(lambda cut: args.min_len <= cut.duration <= args.max_len)
    return cuts.map(lambda cut: tokenize_text(cut, tokenizer=tokenizer))


def build_dataloader(args: argparse.Namespace, cuts: CutSet, shuffle: bool) -> torch.utils.data.DataLoader:
    dm_args = SimpleNamespace(
        on_the_fly_feats=True,
        bucketing_sampler=True,
        max_duration=args.max_duration,
        shuffle=shuffle,
        num_buckets=args.num_buckets,
        drop_last=shuffle,
        return_cuts=True,
        num_workers=args.num_workers if shuffle else max(1, min(args.num_workers, 2)),
        input_strategy="PrecomputedFeatures",
    )
    datamodule = TtsDataModule(dm_args)
    return datamodule.train_dataloaders(cuts) if shuffle else datamodule.dev_dataloaders(cuts)


def save_model_checkpoint(path: Path, model: ZipVoice, optimizer: torch.optim.Optimizer, scaler: GradScaler, batch_idx: int, valid_loss: float) -> None:
    save_checkpoint(
        filename=path,
        model=model,
        params={"batch_idx_train": batch_idx, "valid_loss": valid_loss},
        optimizer=optimizer,
        scaler=scaler,
    )


def copy_runtime_files(args: argparse.Namespace) -> None:
    shutil.copyfile(args.model_config, args.exp_dir / "model.json")
    shutil.copyfile(args.token_file, args.exp_dir / "tokens.txt")
    (args.exp_dir / "run_config.json").write_text(
        json.dumps(vars(args), ensure_ascii=False, indent=2, default=str) + "\n",
        encoding="utf-8",
    )


def setup_logging(exp_dir: Path) -> None:
    formatter = "%(asctime)s %(levelname)s [%(filename)s:%(lineno)d] %(message)s"
    handlers = [
        logging.StreamHandler(),
        logging.FileHandler(exp_dir / "train.log", encoding="utf-8"),
    ]
    logging.basicConfig(format=formatter, level=logging.INFO, handlers=handlers, force=True)


if __name__ == "__main__":
    main()
